version: 1.0.{build}
image: Visual Studio 2017
environment:
  PYTHON: C:\Python37-x64
  PYTHON_VERSION: 3.7.1
  PYTHON_ARCH: 64
  CONAN_UPLOAD: https://api.bintray.com/conan/kudzurunner/conan-stable
  CONAN_REMOTE: conan-stable
  CONAN_REFERENCE: strawberryperl/5.28.1.1
  CONAN_USERNAME: kudzurunner
  CONAN_CHANNEL: stable
  CONAN_PASSWORD:
    secure: FHRzS1Qt5LEb3S+po6y9BkjaPm/d5gv56M9ZC90wpJVIJs/f4ljLdVoXhbqk4jEZ
install:
  - cmd: >-
      set PATH=%PATH%;%PYTHON%/Scripts/

      pip install conan --upgrade

      pip install conan_package_tools

      conan remote add conan-stable https://api.bintray.com/conan/kudzurunner/conan-stable

      conan user
build: off
test_script:
  - cmd: python build.py
deploy: off